modLoader="javafml"
license="LGPLv3"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/GregTech-Intergalactical/AntimatterAPI/issues"

[[mods]]
modId="antimatter"
version="${version}"
displayName="AntimatterAPI"
displayURL="https://github.com/GregTech-Intergalactical/AntimatterAPI"
#logoFile="examplemod.png"
credits="mitchej123, e99999, qubka, Vliro, repolainen, Trinsdar for general implementations/fixes"
authors="Muramasa, Rongmario"
description='''Well-rounded API for Minecraft, primarily made for GregTech.'''
[custom.mc-publish]
curseforge=462713
[[dependencies.antimatter]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.64,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.antimatter]]
    modId="tesseractapi"
    mandatory=true
    versionRange="[0.0.4,)"
    ordering="AFTER"
    side="BOTH"
    [dependencies.antimatter.custom.mc-publish]
        ignore=false
        curseforge="tesseractapi"
[[dependencies.antimatter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.antimatter]]
    modId="kubejs"
    mandatory=false
    versionRange="[1605,)"
    ordering="AFTER"
    side="BOTH"
[[mods]]
modId="antimatter_shared"
version="${version}"
displayName="Antimatter Shared Data"
displayURL="https://github.com/GregTech-Intergalactical/AntimatterAPI"
#logoFile="examplemod.png"
credits="mitchej123, e99999, qubka, Vliro, repolainen, Trinsdar for general implementations/fixes"
authors="Muramasa, Rongmario"
description='''Modid used for data shared betwen antimatter addons'''
[[dependencies.antimatter_shared]]
    modId="antimatter"
    mandatory=true
    versionRange="[0.0.1,)"
    ordering="AFTER"
    side="BOTH"