modLoader="javafml"
#loaderVersion="[${loader_version},)"
license="LGPLv3"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/GregTech-Intergalactical/AntimatterAPI/issues"

[[mods]]
modId="antimatter"
#version="${version}"
version="0.1"
displayName="AntimatterAPI"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/GregTech-Intergalactical/AntimatterAPI"
#logoFile="examplemod.png"
credits="mitchej123, e99999, qubka, abbeswag, repolainen for general implementations/fixes"
authors="Muramasa, Rongmario"
description='''Well-rounded API for Minecraft, primarily made for GregTech.'''
[[dependencies.antimatter]]
    modId="forge"
    mandatory=true
    #versionRange="[${forge_version},)"
    versionRange="31.0.1"
    ordering="NONE"
    side="BOTH"
[[dependencies.antimatter]]
    modId="minecraft"
    mandatory=true
    #versionRange="[${minecraft_version}]"
    versionRange="1.15.2"
    ordering="NONE"
    side="BOTH"