modLoader="javafml"
#loaderVersion="[${loader_version},)"
loaderVersion="[31,)"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="antimatter"
#version="${version}"
version="0.0.1"
displayName="Antimatter API"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="examplemod.png"
credits="GregoriusTechneticies for his work on GregTech"
authors="Muramasa"
description='''The foundation API for GTI'''
[[dependencies.antimatter]]
    modId="forge"
    mandatory=true
    #versionRange="[${forge_version},)"
    versionRange="31.0.1"
    ordering="NONE"
    side="BOTH"
[[dependencies.antimatter]]
    modId="minecraft"
    mandatory=true
    #versionRange="[${minecraft_version}]"
    versionRange="1.15.2"
    ordering="NONE"
    side="BOTH"